blank_issues_enabled: false
contact_links:
  - name: 提问 / Questions
    url: https://github.com/KuekHaoYang/KVideo/discussions/new?category=q-a
    about: 如果你有关于项目的问题，请在这里提问。
  - name: 安全漏洞 / Security Vulnerability
    url: https://github.com/KuekHaoYang/KVideo/security/advisories/new
    about: 报告安全漏洞。
